import {PERMISSIONS} from "./index";

export const brandAdminPermissions = [
    PERMISSIONS.BRAND.VIEW.ID,
    PERMISSIONS.BRAND.UPDATE.ID,
    PERMISSIONS.BRAND.DELETE.ID,

    PERMISSIONS.GYM.CREATE.ID,
    PERMISSIONS.GYM.UPDATE.ID,
    PERMISSIONS.GYM.VIEW.ID,
    PERMISSIONS.GYM.DELETE.ID,

    PERMISSIONS.LEAD.UPSERT.ID,
    PERMISSIONS.LEAD.VIEW.ID,
    PERMISSIONS.LEAD.DELETE.ID,

    PERMISSIONS.CUSTOMER.UPSERT.ID,
    PERMISSIONS.CUSTOMER.VIEW.ID,

    PERMISSIONS.INSTRUCTOR.UPSERT.ID,
    PERMISSIONS.INSTRUCTOR.VIEW.ID,
    PERMISSIONS.INSTRUCTOR.DELETE.ID,

    PERMISSIONS.ADMIN.UPSERT.ID,
    PERMISSIONS.ADMIN.VIEW.ID,
    PERMISSIONS.ADMIN.DELETE.ID,

    PERMISSIONS.MEMBERSHIP_PLAN_GROUP.UPSERT.ID,
    PERMISSIONS.MEMBERSHIP_PLAN_GROUP.VIEW.ID,
    PERMISSIONS.MEMBERSHIP_PLAN_GROUP.DELETE.ID,

    PERMISSIONS.MEMBERSHIP_PLAN.UPSERT.ID,
    PERMISSIONS.MEMBERSHIP_PLAN.VIEW.ID,
    PERMISSIONS.MEMBERSHIP_PLAN.DELETE.ID,

    PERMISSIONS.PAYMENT_PLAN.UPSERT.ID,
    PERMISSIONS.PAYMENT_PLAN.VIEW.ID,
    PERMISSIONS.PAYMENT_PLAN.DELETE.ID,

    PERMISSIONS.SERVICE.UPSERT.ID,
    PERMISSIONS.SERVICE.VIEW.ID,
    PERMISSIONS.SERVICE.DELETE.ID,

    PERMISSIONS.PAYMENTS.VIEW.ID,

    PERMISSIONS.SESSION_CONTRACT.UPSERT.ID,
    PERMISSIONS.SESSION_CONTRACT.VIEW.ID,
    PERMISSIONS.SESSION_CONTRACT.DELETE.ID,
    PERMISSIONS.SESSION_CONTRACT.PAY.ID,
    PERMISSIONS.SESSION_CONTRACT.BOOK.ID,

    PERMISSIONS.CLASS.UPSERT.ID,
    PERMISSIONS.CLASS.VIEW.ID,
    PERMISSIONS.CLASS.DELETE.ID,
    PERMISSIONS.CLASS.PURCHASE.ID,

    PERMISSIONS.CLASS_SCHEDULE.UPSERT.ID,
    PERMISSIONS.CLASS_SCHEDULE.VIEW.ID,
    PERMISSIONS.CLASS_SCHEDULE.DELETE.ID,
    PERMISSIONS.CLASS_SCHEDULE.ATTEND.ID,
    PERMISSIONS.CLASS_SCHEDULE.MODIFY.ID,
    PERMISSIONS.CLASS_SCHEDULE.MARK_DONE.ID,

    PERMISSIONS.DISCOUNT.UPSERT.ID,
    PERMISSIONS.DISCOUNT.VIEW.ID,
    PERMISSIONS.DISCOUNT.DELETE.ID,

    PERMISSIONS.MEMBERSHIP.LIST.ID,
    PERMISSIONS.MEMBERSHIP.PURCHASE.ID,
    PERMISSIONS.MEMBERSHIP.CANCEL.ID,
    PERMISSIONS.MEMBERSHIP.TRANSFER.ID,
    PERMISSIONS.MEMBERSHIP.FREEZE.ID,
    PERMISSIONS.MEMBERSHIP.UNFREEZE.ID,

    PERMISSIONS.GYM_QR_SESSION.UPSERT.ID,
    PERMISSIONS.GYM_QR_SESSION.VIEW.ID,

    PERMISSIONS.SUBSCRIPTION.PURCHASE.ID,

    PERMISSIONS.EXPENSE.VIEW.ID,
    PERMISSIONS.EXPENSE.UPSERT.ID,
    PERMISSIONS.EXPENSE.DELETE.ID,

    PERMISSIONS.PT_COMMISSION.VIEW.ID,
    PERMISSIONS.PT_COMMISSION.UPSERT.ID,

    PERMISSIONS.CLASS_COMMISSION.VIEW.ID,
    PERMISSIONS.CLASS_COMMISSION.UPSERT.ID,

    PERMISSIONS.PT_COMMISSION_REPORT.VIEW.ID,
    PERMISSIONS.CLASS_COMMISSION_REPORT.VIEW.ID,
]