import {PERMISSIONS} from "./index";

export const ptAdminPermissions = [

    PERMISSIONS.GYM.VIEW.ID,
    PERMISSIONS.LEAD.UPSERT.ID,
    PERMISSIONS.LEAD.VIEW.ID,
    PERMISSIONS.CUSTOMER.VIEW.ID,
    PERMISSIONS.INSTRUCTOR.VIEW.ID,
    PERMISSIONS.ADMIN.VIEW.ID,
    PERMISSIONS.SERVICE.VIEW.ID,
    PERMISSIONS.SESSION_CONTRACT.UPSERT.ID,
    PERMISSIONS.SESSION_CONTRACT.VIEW.ID,
    PERMISSIONS.CLASS.VIEW.ID,
    PERMISSIONS.CLASS_SCHEDULE.VIEW.ID,
    PERMISSIONS.CLASS_SCHEDULE.ATTEND.ID,
    PERMISSIONS.CLASS_SCHEDULE.MARK_DONE.ID,
    PERMISSIONS.GYM_QR_SESSION.UPSERT.ID,
    PERMISSIONS.GYM_QR_SESSION.VIEW.ID,
    PERMISSIONS.PT_COMMISSION.VIEW.ID,
    PERMISSIONS.CLASS_COMMISSION.VIEW.ID,
    PERMISSIONS.PT_COMMISSION_REPORT.VIEW.ID,
    PERMISSIONS.CLASS_COMMISSION_REPORT.VIEW.ID,
]