
type User {
    id: ID!
    uuid: String!
    roleId: String!
    firstName: String!
    middleName: String
    lastName: String
    email: String!
    countryId: Int!
    phoneCode: String
    phoneNumber: String
    gender: Gender
    status: Status!
    photo: String
    inviteLink: String
    inviteExpiry: Datetime
    biometricUserId: String
    createdById: String!
    lastUpdatedById: String
    createdAt: Datetime!
    updatedAt: Datetime!
    isSysAdmin: Boolean!

    # Relations
    role: Role!
    createdBy: User
    lastUpdatedBy: User
}